const DIARY_KEY = 'yuri-frontpage-diary-demo-v1';
const COMMENT_KEY = 'yuri-frontpage-comments-demo-v1';
const seedPosts = [
  { id: 'codex-demo', date: '2026-09-17', title: 'ローカル投稿テスト', author: 'Codex', image: '../images/meat-bun.jpeg', body: '管理人室から日記を書いてみました。\n\nこれはプロジェクトに保存したテスト投稿です。写真も貼れるようにしてみました。' },
  { id: 'welcome', date: '2026-09-17', title: '日記のページを作ってみました', author: 'Yuri', body: '今日はホームページに日記のページを作ってみました。\n\n小さい花の背景にしたら、少しだけ女の子のホームページみたいになったかも…。でも気に入っています。\n\nこれから、写真や日々のことを少しずつ書けたらいいなと思います。' },
  { id: 'links', date: '2026-09-12', title: '久しぶりにサイトを見直しました', author: 'Yuri', body: '久しぶりにサイトを見直しました。リンクが多いと、やっぱりホームページらしいです。\n\n次は写真のページも作りたいです。' }
];
const seedComments = [
  { id: 'codex-demo', name: 'テスト訪問者', body: '日記を読みに来ました。背景がかわいいです！', createdAt: '2026-09-17T05:23:36.000Z' },
  { id: 'bbs', name: 'Codex', body: 'BBS も作ってみました。よかったら足跡を残してくださいね。', createdAt: '2026-09-17T05:41:07.000Z' }
];
function load(key) { try { return JSON.parse(localStorage.getItem(key)) || []; } catch { return []; } }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function commentsFor(id) { const seen = new Set(); return [...load(COMMENT_KEY), ...seedComments].filter(c => c.id === id && !seen.has(`${c.name}|${c.body}`) && seen.add(`${c.name}|${c.body}`)); }
function posts() { return [...load(DIARY_KEY), ...seedPosts].sort((a, b) => b.date.localeCompare(a.date)); }
function esc(value) { const el = document.createElement('span'); el.textContent = value; return el.innerHTML; }
function dateText(value) { return new Date(value + 'T00:00:00').toLocaleDateString('ja-JP', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' }); }
function renderDiaryList() { const target = document.querySelector('#dynamic-entries'); if (!target) return; target.innerHTML = posts().map((p, i) => `<article class="entry"><h2><a href="./entry.html?id=${encodeURIComponent(p.id)}">${dateText(p.date)}　${esc(p.title)}</a>${i === 0 ? ' <span class="new">NEW!</span>' : ''}</h2>${p.image ? `<img class="entry-thumb" src="${esc(p.image)}" alt="日記の写真">` : ''}<p>${esc(p.body).split('\n\n')[0].replace(/\n/g, '<br>')}</p><p align="right"><a href="./entry.html?id=${encodeURIComponent(p.id)}">≫ 続きを読む</a></p></article>`).join(''); }
function renderComments(postId) { const target = document.querySelector('#comments'); if (!target) return; const comments = commentsFor(postId); target.innerHTML = comments.length ? comments.map(c => `<div class="comment"><span class="comment-name">${esc(c.name)}</span> <span class="comment-date">${new Date(c.createdAt).toLocaleString('ja-JP')}</span><br>${esc(c.body).replace(/\n/g, '<br>')}</div>`).join('') : '<p class="note">まだ書き込みはありません。よかったら一言どうぞ。</p>'; }
function setupBbs() { const target = document.querySelector('#bbs-messages'); const form = document.querySelector('#bbs-form'); if (!target || !form) return; const render = () => { const comments = commentsFor('bbs'); target.innerHTML = comments.length ? comments.map(c => `<div class="comment"><span class="comment-name">${esc(c.name)}</span> <span class="comment-date">${new Date(c.createdAt).toLocaleString('ja-JP')}</span><br>${esc(c.body).replace(/\n/g, '<br>')}</div>`).join('') : '<p class="note">まだ書き込みはありません。はじめの一人になってね。</p>'; }; render(); form.addEventListener('submit', e => { e.preventDefault(); const d = new FormData(form), body = String(d.get('body')).trim(); if (!body) return; const all = load(COMMENT_KEY); all.unshift({ id: 'bbs', name: String(d.get('name')).trim() || '名無しさん', body, createdAt: new Date().toISOString() }); save(COMMENT_KEY, all); form.reset(); render(); }); }
function renderEntry() { const target = document.querySelector('#entry-content'); if (!target) return; const id = new URLSearchParams(location.search).get('id'); const post = posts().find(p => p.id === id) || seedPosts[0]; document.title = `${post.title} - 管理人の日記`; target.innerHTML = `<p class="content-title">■ ${dateText(post.date)}</p><article class="entry"><h2>${esc(post.title)}</h2>${esc(post.body).split('\n\n').map(p => `<p>${p.replace(/\n/g, '<br>')}</p>`).join('')}${post.image ? `<img class="diary-photo" src="${esc(post.image)}" alt="日記の写真">` : ''}<hr><p align="right">管理人 ${esc(post.author || 'Yuri')}　(^_^)/</p></article>`; renderComments(post.id); const form = document.querySelector('#comment-form'); form?.addEventListener('submit', e => { e.preventDefault(); const d = new FormData(form), body = String(d.get('body')).trim(); if (!body) return; const all = load(COMMENT_KEY); all.unshift({ id: post.id, name: String(d.get('name')).trim() || '名無しさん', body, createdAt: new Date().toISOString() }); save(COMMENT_KEY, all); form.reset(); renderComments(post.id); }); }
function setupStation() { const form = document.querySelector('#post-form'); if (!form) return; form.date.value = new Date().toISOString().slice(0, 10); form.addEventListener('submit', e => { e.preventDefault(); const d = new FormData(form), p = { id: `local-${Date.now()}`, date: String(d.get('date')), title: String(d.get('title')).trim(), author: String(d.get('author')).trim() || 'Yuri', body: String(d.get('body')).trim() }; if (!p.title || !p.body) return; const image = d.get('image'); if (image instanceof File && image.size) { const reader = new FileReader(); reader.onload = () => { p.image = reader.result; const all = load(DIARY_KEY); all.unshift(p); save(DIARY_KEY, all); location.href = `./entry.html?id=${encodeURIComponent(p.id)}`; }; reader.readAsDataURL(image); return; } const all = load(DIARY_KEY); all.unshift(p); save(DIARY_KEY, all); location.href = `./entry.html?id=${encodeURIComponent(p.id)}`; }); }
renderDiaryList(); renderEntry(); setupStation(); setupBbs();
